version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.19.0

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Dependencies
          command: npm install

      # Run lint on PR and main branch
      - run:
          name: Run Lint
          command: npm run lint

workflows:
  version: 2
  lint:
    jobs:
      - build
